/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lynn.demo.book.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Books service. Represents a row in the &quot;book_Books&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lynn.demo.book.model.impl.BooksModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lynn.demo.book.model.impl.BooksImpl}.
 * </p>
 *
 * @author 10295
 * @see Books
 * @see com.lynn.demo.book.model.impl.BooksImpl
 * @see com.lynn.demo.book.model.impl.BooksModelImpl
 * @generated
 */
public interface BooksModel extends BaseModel<Books>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a books model instance should use the {@link Books} interface instead.
	 */

	/**
	 * Returns the primary key of this books.
	 *
	 * @return the primary key of this books
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this books.
	 *
	 * @param primaryKey the primary key of this books
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the book ID of this books.
	 *
	 * @return the book ID of this books
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this books.
	 *
	 * @param bookId the book ID of this books
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the group ID of this books.
	 *
	 * @return the group ID of this books
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this books.
	 *
	 * @param groupId the group ID of this books
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this books.
	 *
	 * @return the company ID of this books
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this books.
	 *
	 * @param companyId the company ID of this books
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this books.
	 *
	 * @return the user ID of this books
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this books.
	 *
	 * @param userId the user ID of this books
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this books.
	 *
	 * @return the user uuid of this books
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this books.
	 *
	 * @param userUuid the user uuid of this books
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this books.
	 *
	 * @return the user name of this books
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this books.
	 *
	 * @param userName the user name of this books
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this books.
	 *
	 * @return the create date of this books
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this books.
	 *
	 * @param createDate the create date of this books
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this books.
	 *
	 * @return the modified date of this books
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this books.
	 *
	 * @param modifiedDate the modified date of this books
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the book name of this books.
	 *
	 * @return the book name of this books
	 */
	@AutoEscape
	public String getBookName();

	/**
	 * Sets the book name of this books.
	 *
	 * @param bookName the book name of this books
	 */
	public void setBookName(String bookName);

	/**
	 * Returns the price of this books.
	 *
	 * @return the price of this books
	 */
	public double getPrice();

	/**
	 * Sets the price of this books.
	 *
	 * @param price the price of this books
	 */
	public void setPrice(double price);

	/**
	 * Returns the book s n of this books.
	 *
	 * @return the book s n of this books
	 */
	@AutoEscape
	public String getBookSN();

	/**
	 * Sets the book s n of this books.
	 *
	 * @param bookSN the book s n of this books
	 */
	public void setBookSN(String bookSN);

	/**
	 * Returns the content of this books.
	 *
	 * @return the content of this books
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this books.
	 *
	 * @param content the content of this books
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Books books);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Books> toCacheModel();

	@Override
	public Books toEscapedModel();

	@Override
	public Books toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}